// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmhaiycolbydemwnbfdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtaGFpeWNvbGJ5ZGVtd25iZmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxODE2MDksImV4cCI6MjA1MDc1NzYwOX0.rTOmEAgJmSuZI2cefe4MaLkBXkAf4wtRoncLAeVPtdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);